name: Bug report 🚩
description: Create a report to help us improve
title: "[BUG] "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out our bug report form."

  - type: textarea
    attributes:
      label: Environment
      value: |
        - **qBraid version**:
        - **Python version**:
        - **Operating system**:
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: What happened?
      description: Please provide a detailed description of the bug, accompanied by a minimal code example that demonstrates how the error(s) can be reproduced.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggestions (Optional)
      description: We warmly welcome any recommendations on potential fixes, insights, or considerations that contributors should keep in mind when working to resolve this issue.
    validations:
      required: false