# Copyright 2025 qBraid
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Module defining conversions from OpenFermion ``QubitOperator`` to the other Pauli-operator types.

Generated by ``bin/generate_operator_conversions.py``; edit that script, not this file.

"""
from __future__ import annotations

from typing import TYPE_CHECKING

from qbraid.transpiler.annotations import weight
from qbraid.transpiler.conversions._pauli_io import (
    read_openfermion_qubit,
    write_braket_observable,
    write_cirq_pauli,
    write_cudaq_spin,
    write_pennylane_pauli,
    write_qiskit_pauli,
)

if TYPE_CHECKING:
    import braket.circuits.observable
    import cirq
    import cudaq
    import openfermion
    import pennylane
    from qiskit.quantum_info import SparsePauliOp


@weight(1)
def openfermion_qubit_to_braket_observable(
    op: openfermion.QubitOperator,
) -> braket.circuits.observable.Observable:
    """Convert an OpenFermion ``QubitOperator`` to an Amazon Braket ``Observable``."""
    return write_braket_observable(read_openfermion_qubit(op))


@weight(1)
def openfermion_qubit_to_cirq_pauli(op: openfermion.QubitOperator) -> cirq.PauliSum:
    """Convert an OpenFermion ``QubitOperator`` to a Cirq ``PauliSum``."""
    return write_cirq_pauli(read_openfermion_qubit(op))


@weight(1)
def openfermion_qubit_to_cudaq_spin(op: openfermion.QubitOperator) -> cudaq.SpinOperator:
    """Convert an OpenFermion ``QubitOperator`` to a CUDA-Q ``SpinOperator``."""
    return write_cudaq_spin(read_openfermion_qubit(op))


@weight(1)
def openfermion_qubit_to_pennylane_pauli(
    op: openfermion.QubitOperator,
) -> pennylane.pauli.PauliSentence:
    """Convert an OpenFermion ``QubitOperator`` to a PennyLane ``PauliSentence``."""
    return write_pennylane_pauli(read_openfermion_qubit(op))


@weight(1)
def openfermion_qubit_to_qiskit_pauli(op: openfermion.QubitOperator) -> SparsePauliOp:
    """Convert an OpenFermion ``QubitOperator`` to a Qiskit ``SparsePauliOp``."""
    return write_qiskit_pauli(read_openfermion_qubit(op))
