# Copyright 2025 qBraid
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Module defining conversions from CUDA-Q ``SpinOperator`` to the other Pauli-operator types.

Generated by ``bin/generate_operator_conversions.py``; edit that script, not this file.

"""
from __future__ import annotations

from typing import TYPE_CHECKING

from qbraid.transpiler.annotations import weight
from qbraid.transpiler.conversions._pauli_io import (
    read_cudaq_spin,
    write_braket_observable,
    write_cirq_pauli,
    write_openfermion_qubit,
    write_pennylane_pauli,
    write_qiskit_pauli,
)

if TYPE_CHECKING:
    import braket.circuits.observable
    import cirq
    import cudaq
    import openfermion
    import pennylane
    from qiskit.quantum_info import SparsePauliOp


@weight(1)
def cudaq_spin_to_braket_observable(
    op: cudaq.SpinOperator,
) -> braket.circuits.observable.Observable:
    """Convert a CUDA-Q ``SpinOperator`` to an Amazon Braket ``Observable``."""
    return write_braket_observable(read_cudaq_spin(op))


@weight(1)
def cudaq_spin_to_cirq_pauli(op: cudaq.SpinOperator) -> cirq.PauliSum:
    """Convert a CUDA-Q ``SpinOperator`` to a Cirq ``PauliSum``."""
    return write_cirq_pauli(read_cudaq_spin(op))


@weight(1)
def cudaq_spin_to_openfermion_qubit(op: cudaq.SpinOperator) -> openfermion.QubitOperator:
    """Convert a CUDA-Q ``SpinOperator`` to an OpenFermion ``QubitOperator``."""
    return write_openfermion_qubit(read_cudaq_spin(op))


@weight(1)
def cudaq_spin_to_pennylane_pauli(op: cudaq.SpinOperator) -> pennylane.pauli.PauliSentence:
    """Convert a CUDA-Q ``SpinOperator`` to a PennyLane ``PauliSentence``."""
    return write_pennylane_pauli(read_cudaq_spin(op))


@weight(1)
def cudaq_spin_to_qiskit_pauli(op: cudaq.SpinOperator) -> SparsePauliOp:
    """Convert a CUDA-Q ``SpinOperator`` to a Qiskit ``SparsePauliOp``."""
    return write_qiskit_pauli(read_cudaq_spin(op))
