# Copyright 2025 qBraid
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Module defining conversions from Qiskit ``SparsePauliOp`` to the other Pauli-operator types.

Generated by ``bin/generate_operator_conversions.py``; edit that script, not this file.

"""
from __future__ import annotations

from typing import TYPE_CHECKING

from qbraid.transpiler.annotations import weight
from qbraid.transpiler.conversions._pauli_io import (
    read_qiskit_pauli,
    write_braket_observable,
    write_cirq_pauli,
    write_cudaq_spin,
    write_openfermion_qubit,
    write_pennylane_pauli,
)

if TYPE_CHECKING:
    import braket.circuits.observable
    import cirq
    import cudaq
    import openfermion
    import pennylane
    from qiskit.quantum_info import SparsePauliOp


@weight(1)
def qiskit_pauli_to_braket_observable(op: SparsePauliOp) -> braket.circuits.observable.Observable:
    """Convert a Qiskit ``SparsePauliOp`` to an Amazon Braket ``Observable``."""
    return write_braket_observable(read_qiskit_pauli(op))


@weight(1)
def qiskit_pauli_to_cirq_pauli(op: SparsePauliOp) -> cirq.PauliSum:
    """Convert a Qiskit ``SparsePauliOp`` to a Cirq ``PauliSum``."""
    return write_cirq_pauli(read_qiskit_pauli(op))


@weight(1)
def qiskit_pauli_to_cudaq_spin(op: SparsePauliOp) -> cudaq.SpinOperator:
    """Convert a Qiskit ``SparsePauliOp`` to a CUDA-Q ``SpinOperator``."""
    return write_cudaq_spin(read_qiskit_pauli(op))


@weight(1)
def qiskit_pauli_to_openfermion_qubit(op: SparsePauliOp) -> openfermion.QubitOperator:
    """Convert a Qiskit ``SparsePauliOp`` to an OpenFermion ``QubitOperator``."""
    return write_openfermion_qubit(read_qiskit_pauli(op))


@weight(1)
def qiskit_pauli_to_pennylane_pauli(op: SparsePauliOp) -> pennylane.pauli.PauliSentence:
    """Convert a Qiskit ``SparsePauliOp`` to a PennyLane ``PauliSentence``."""
    return write_pennylane_pauli(read_qiskit_pauli(op))
